version: '3'

services:
    ## usage: docker-compose run --rm serve
    ##      : docker-compose up (-d) serve
    serve:
        command: yarn serve
        image: node:16-buster
        ports:
            - 59840:3000
            - 59841:3001
        user: '1000'
        volumes:
            - ./:/src
        working_dir: /src

    ## usage: docker-compose run --rm install
    install:
        command: yarn install
        image: node:16-buster
        user: '1000'
        volumes:
            - ./:/src
        working_dir: /src
